package:
  name: feasst
  version: 0.8.0

source:
  git_url: https://github.com/hhatch/feasst

build:
  number: 0
  script:
    - git checkout hwh/conda
    - mkdir -p build
    - cd build
    - cmake -DUSE_SWIG=ON ..
    - make _feasst -j$CPU_COUNT
    - make install -j$CPU_COUNT

requirements:
  build:
    - python {{ python }}
    - cmake >=3.10.2
    - swig >=3.0.12

#test:
# commands:
#   - mkdir build && cd build && make test

